name: bilal_muezzin_app
description: A Quran app that plays azaan on Google home and other smart speakers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.18.0
  google_fonts: ^5.1.0
  path_provider: ^2.1.0
  url_launcher: ^6.1.12
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/

  fonts:
    - family: ScheherazadeNew
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
        - asset: assets/fonts/ScheherazadeNew-Bold.ttf
          weight: 700
